# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-13 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
